# AutoOps AI - Agent Task Orchestration Workflow
# Dynamic workflow template for agent-generated tasks

id: autoops-agent-workflow
namespace: autoops.agent

description: |
  Dynamic workflow template for executing agent-generated tasks.
  This workflow is customized at runtime based on the decomposed goal.

inputs:
  - id: goal_id
    type: STRING
    required: true
    description: Unique identifier for the goal
  - id: goal_description
    type: STRING
    required: true
    description: Description of the goal
  - id: task_count
    type: INT
    required: true
    description: Number of tasks to execute

variables:
  workflow_start: "{{ now() }}"
  execution_id: "{{ execution.id }}"

tasks:
  - id: initialize
    type: io.kestra.core.tasks.scripts.Bash
    description: Initialize agent workflow
    commands:
      - echo "=== AutoOps AI Agent Workflow ==="
      - echo "Goal ID: {{ inputs.goal_id }}"
      - echo "Goal: {{ inputs.goal_description }}"
      - echo "Tasks: {{ inputs.task_count }}"
      - echo "Starting execution..."

  - id: planning_phase
    type: io.kestra.core.tasks.scripts.Python
    description: Execute planning phase
    dependsOn:
      - initialize
    inputFiles:
      plan.py: |
        import json
        
        print("Planning Phase")
        print("-" * 40)
        print("Analyzing goal...")
        print("Breaking down into tasks...")
        print("Establishing dependencies...")
        print("Creating execution plan...")
        
        plan = {
            "goal": "{{ inputs.goal_description }}",
            "tasks": {{ inputs.task_count }},
            "estimated_duration": {{ inputs.task_count }} * 15,
            "parallel_opportunities": 2
        }
        
        print(json.dumps(plan, indent=2))
    commands:
      - python plan.py

  - id: execution_phase
    type: io.kestra.core.tasks.scripts.Python
    description: Execute all planned tasks
    dependsOn:
      - planning_phase
    inputFiles:
      execute.py: |
        import time
        
        print("Execution Phase")
        print("-" * 40)
        
        for i in range(1, {{ inputs.task_count }} + 1):
            print(f"Task {i}/{{ inputs.task_count }}: Executing...")
            time.sleep(0.5)  # Simulate work
            print(f"Task {i}/{{ inputs.task_count }}: Complete ✓")
        
        print("-" * 40)
        print("All tasks executed successfully")
    commands:
      - python execute.py

  - id: reflection_phase
    type: io.kestra.core.tasks.scripts.Python
    description: Analyze results and generate insights
    dependsOn:
      - execution_phase
    inputFiles:
      reflect.py: |
        import json
        
        print("Reflection Phase")
        print("-" * 40)
        
        reflection = {
            "summary": "Workflow completed successfully",
            "success_rate": 100,
            "insights": [
                "All tasks executed within expected time",
                "No errors encountered during execution",
                "Resource utilization was optimal"
            ],
            "improvements": [
                "Consider parallel execution for independent tasks",
                "Add checkpointing for longer workflows"
            ],
            "score": 95
        }
        
        print(json.dumps(reflection, indent=2))
    commands:
      - python reflect.py

  - id: finalize
    type: io.kestra.core.tasks.scripts.Bash
    description: Finalize workflow execution
    dependsOn:
      - reflection_phase
    commands:
      - echo "=== Workflow Complete ==="
      - echo "Execution ID: {{ variables.execution_id }}"
      - echo "Started: {{ variables.workflow_start }}"
      - echo "Finished: {{ now() }}"
      - echo "Status: SUCCESS"

triggers:
  - id: api_trigger
    type: io.kestra.core.models.triggers.types.Webhook
    key: "autoops-agent-trigger"

errors:
  - id: handle_error
    type: io.kestra.core.tasks.scripts.Bash
    commands:
      - echo "Workflow encountered an error"
      - echo "Logging failure for analysis..."
      - echo "Notifying agent system..."
